### ISSUE TITLE
Token ID still consist of just tokenId

### ISSUE THREAD

**Issue by corlys** [subsquid/squid-astar-example#1]
the token Id thats added to tokensIds set is still just consisting of tokenId without the contract symbol. This will cause the fetching of tokens in tokens mapping to failed, hence the program will always make new token even the token is already exist. Correct me if im wrong guys.

**Comment by RaekwonIII** [comment]
Hey @corlys can you check if this line answers your doubt?
https://github.com/subsquid/squid-astar-example/blob/66e23bf0982483ab557fdcdbb98f0014556a3479/src/processor.ts#L132
I encountered that issue while upgrading this repository to FireSquid and the code in the line I linked seemed to have solved it for me.
Can you please confirm if the issue still persists, or if that line fixes it?

**Comment by corlys** [comment]
Yep i encounter this when working with the on the example given by the docs.
[https://github.com/subsquid/squid-astar-example/blob/66e23bf0982483ab557fdcdbb98f0014556a3479/src/processor.ts#L129](url)
This part is already correct, the code fetch the token from the tokens mapping with the id formatted to `symbol-tokenId`
But in the beginning, when we add to the sets that are used to find the token thats already saved, we still only using the tokenId
[https://github.com/subsquid/squid-astar-example/blob/66e23bf0982483ab557fdcdbb98f0014556a3479/src/processor.ts#L95](url)
when we ran this part of the code, no token will be found.
[https://github.com/subsquid/squid-astar-example/blob/66e23bf0982483ab557fdcdbb98f0014556a3479/src/processor.ts#L103](url)

**Comment by RaekwonIII** [comment]
I see what you are saying! Nice catch, thanks for reporting it and for explaining where the issue lies.
I'll get on fixing that.

**Comment by RaekwonIII** [comment]
@corlys Can you check if this is OK?? I am at a conference, with very crappy wi-fi and laptop...on my lap, so it's a bit hard to test...

https://github.com/subsquid/squid-astar-example/tree/test-token-fix

**Comment by corlys** [comment]
after doing some console logging, it looks alright. The function for making the for the token seems to be working well.

**Comment by RaekwonIII** [comment]
Merged the PR for that branch, closing this issue, thanks again for flagging the issue.
